name: Terraform Actions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"

      - name: Terraform Init
        working-directory: ./files
        run: terraform init

      - name: Terraform Format
        working-directory: ./files
        run: terraform fmt

      - name: Terraform Validate
        working-directory: ./files
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./files
        run: |
          terraform plan \
            -var="username=${{ secrets.TF_VAR_username }}" \
            -var="password=${{ secrets.TF_VAR_password }}" \
            -var="tenant_name=${{ secrets.TF_VAR_tenant_name }}" \
            -out=tfplan
